turf_project/iddo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('turfapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

turf_project/turfapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.userlogin, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add-turf/', views.AddTurf.as_view(), name = 'add_turf'),
    path('turf-list/', views.TurfListView.as_view(), name = 'turf_list'),
    path('turf/<int:pk>/', views.TurfView.as_view(), name = 'turf_detail'),
    path('book/<int:turf_id>/', views.TrufBookView.as_view(), name = 'booking'),
    path('bookings/', views.OwnerTurfBookingsView.as_view(), name = 'bookings'),
    path('bookings/<int:pk>/', views.BookingSuccessView.as_view(), name = "booking-detail"),
    path('my-bookings/', views.UserTurfBookingsView.as_view(), name= 'my-bookings'),
    path('check-availablity/', views.check_booking_availability, name = 'check-availability'),
    path('details/', views.createpost, name='details'),
    path('show/', views.showvideo, name='show')
]

turf_project/turfapp/models.py
from django.db import models
import datetime
from django.core.validators import MinValueValidator
# Create your models here.

class Profile(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female')
    )
    user = models.OneToOneField('auth.User', on_delete = models.CASCADE)
    gender = models.CharField(max_length = 1, choices = GENDER_CHOICES ,null = True)
    phone = models.CharField(max_length = 10)
    address = models.TextField()
    is_owner = models.BooleanField(default = False)
    

class TurfImages(models.Model):
    image = models.ImageField(upload_to = 'turf_images/', null = True, blank = True)

class Turf(models.Model):
    owner = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    images = models.ManyToManyField('TurfImages')
    rent_per_hour = models.PositiveIntegerField()
    name = models.CharField(max_length = 150)
    address = models.TextField()
    longitude = models.DecimalField(max_digits = 9, decimal_places = 6)
    latitude = models.DecimalField(max_digits = 9, decimal_places = 6)

class Bookings(models.Model):
    user = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    turf = models.ForeignKey(Turf, on_delete = models.CASCADE)
    date = models.DateField(validators=[MinValueValidator(datetime.date.today)])
    time_from = models.TimeField()
    time_to = models.TimeField()
    order_id = models.CharField(unique=True, max_length=40, null=True, blank=True, default=None) 
    razorpay_order_id = models.CharField(max_length=40, null=True, blank=True)
    razorpay_payment_id = models.CharField(max_length=40, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=500, null=True, blank=True)


class notifications(models.Model):
    user = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    matter=models.CharField(max_length=100)
    file=models.FileField()

class owner(models.Model):
    ownerid=models.AutoField(primary_key=True)
    ownername=models.CharField(max_length=100)
    date=models.DateField()
    time=models.TimeField()
    Place=models.CharField(max_length=100)
    cost=models.IntegerField()
    image=models.ImageField()
    contact=models.IntegerField()
    email=models.EmailField(max_length=20)
    remarks=models.CharField(max_length=10)

class Post(models.Model):
    username= models.CharField(max_length=100, unique=True,default='')
    ownername=models.CharField(max_length=100,default='')
    contact=models.CharField(max_length=100,default='')
    turfdetails= models.CharField(max_length=100, unique=True,default='')
    complaint= models.TextField()
    

turf_project/turfapp/forms.py
from django import forms
from django.forms.widgets import PasswordInput
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

GENDER= [
    ('female', 'female'),
    ('male', 'male'),
    ('others', 'others'),
]

class UserForm(UserCreationForm):
    username=forms.CharField(help_text=None,label='username')
    email=forms.EmailField(label='email')
    phone=forms.CharField(label='Phone')
    address= forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20}))
    gender= forms.CharField(label='select gender', widget=forms.Select(choices=GENDER))
    password1=forms.CharField(help_text=None,widget=PasswordInput,label='Password')
    password2=forms.CharField(help_text=None,widget=PasswordInput,label='Confirm Password')
    are_you_turf_owner = forms.BooleanField(required = False)

    class Meta:
        model=User
        fields=('username','email','phone','address','gender','password1','password2')

class TurfForm(forms.ModelForm):
    class Meta:
        model = models.Turf
        exclude = ('id', 'images')
        widgets = {
            'owner': forms.HiddenInput(),
        }
        
class DateInput(forms.DateInput):
    input_type = 'date'

class BookingForm(forms.ModelForm):
    class Meta:
        model = models.Bookings
        exclude = ('id', )
        widgets = {
            'user': forms.HiddenInput(),
            'turf': forms.HiddenInput(),
            'date': DateInput(),
            # 'time_from': forms.TimeInput(attrs={'type': 'time'}),
            # 'time_to': forms.TimeInput(attrs={'type': 'time'}),
            'time_from': forms.HiddenInput(),
            'time_to': forms.HiddenInput(),
            'razorpay_order_id': forms.HiddenInput(),
            'razorpay_payment_id': forms.HiddenInput(),
            'razorpay_signature': forms.HiddenInput(),
            'order_id': forms.HiddenInput(),
        }

turf_project/turfapp/views.py
from audioop import reverse
import razorpay
from django.contrib.auth import authenticate, login
# from pyexpat.errors import messages
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from .forms import *
from . import models
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import FormView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth import logout as auth_logout
from django.http import HttpResponse
from django.conf import settings
# Create your views here.
from django.contrib import messages
from .models import Post

def index(request):
    return render(request,'index.html')

def register(request):
    if request.method=='POST':
        
        user_form=UserForm(request.POST)

        if user_form.is_valid():
            user=user_form.save()
            user.save()
            # print(user_form.cleaned_data)
            address = user_form.cleaned_data.get('address')
            gender = user_form.cleaned_data.get('select_gender')
            is_owner = user_form.cleaned_data.get('are_you_turf_owner')
            profile = models.Profile.objects.create(
                user = user,
                address = address,
                gender = gender,
                is_owner = is_owner,
            )
            print(profile)

            messages.success(request,'Thank You For Registering')
            return redirect('index')
            #return render(request,'register.html',context={'user_form':user_form,'message':'Registration Success'})

        else:
            HttpResponse('invalid form')
    else:
        user_form=UserForm()
        #profile_form=ProfileForm()
       
    return render(request,'register.html',context={'user_form':user_form})
    


def userlogin(request):
    if request.method=='POST':
        form=AuthenticationForm(request, data=request.POST)
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                if user.profile.is_owner:
                    messages.success(request, "You're owner!")
                login(request,user)
                return redirect('dashboard')
            else:
                return HttpResponse('not active')
        else:
            messages.error(request,'invalid username or password')
            return redirect('login')


    form = AuthenticationForm()
    return render(request=request, template_name="login.html", context={"login_form":form})


def logout(request):
    auth_logout(request)
    return render(request,"index.html")

def dashboard(request):
    return render(request,"dashboard.html")


class AddTurf(LoginRequiredMixin, FormView):
    form_class = TurfForm
    template_name = 'turf/add_turf.html'
    success_url = reverse_lazy('add_turf')

    def get_success_url(self):
        return reverse_lazy('turf_detail', kwargs = {'pk': self.object.id})

    def get_initial(self):
        intials =  super().get_initial()
        intials.update({
            'owner': self.request.user,
        })
        return intials
       
    def form_valid(self, form):
        self.object = form.save()
        images = self.request.FILES.getlist('image')
        for img in images:
            t_image = models.TurfImages.objects.create()
            t_image.image.save(img.name, img)
            self.object.images.add(t_image)
            self.object.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class TurfView(LoginRequiredMixin, DetailView):
    model = models.Turf
    template_name = 'turf/turf_detail.html'


class TurfListView(LoginRequiredMixin, ListView):
    model = models.Turf
    template_name = 'turf/turf_list.html'

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        self.object_list = models.Turf.objects.filter(name__icontains = name)
        context = self.get_context_data()
        return self.render_to_response(context)

def check_booking_availability(request):
    turf_id = request.GET.get('turf_id')
    turf = models.Turf.objects.get(id = turf_id)
    available_bookings_on_this_day = models.Bookings.objects.filter(date = request.GET.get('date'), turf = turf)
    already_booked_slot  = available_bookings_on_this_day.filter(time_from = request.GET.get('time_from'))
    length_of_booked_slot = len(already_booked_slot)
    if(length_of_booked_slot == 0):
        return HttpResponse("ok")
    else:
        return HttpResponse("failed")


class BookingSuccessView(LoginRequiredMixin, DetailView):
    model = models.Bookings
    template_name = 'turf/booking_details.html'

class TrufBookView(LoginRequiredMixin, FormView):
    form_class = BookingForm
    template_name = 'turf/booking_form.html'
    success_url = reverse_lazy('turf_list')

    def get_success_url(self) -> str:
        return reverse_lazy('booking-detail', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        turf_id = self.kwargs.get('turf_id')
        turf = models.Turf.objects.get(id = turf_id)
        available_bookings_on_this_day = models.Bookings.objects.filter(date = self.request.POST.get('date'),  turf= turf)
        already_booked_slot  = available_bookings_on_this_day.filter(time_from = self.request.POST.get('time_from'))
        length_of_booked_slot = len(already_booked_slot)
        # if(length_of_booked_slot == 0):
        messages.success(self.request, 'Your Booking  submitted')
        self.object = form.save()
        models.notifications.objects.create(
            user = self.object.turf.owner,
            matter = f'New booking form user {self.object.user.username}'
        )
        return super().form_valid(form)
        # else:
        #     raise forms.ValidationError("This time slot is already booked")

    def get_context_data(self, **kwargs):
        client = razorpay.Client(auth = (settings.RAZORPAY_ID, settings.RAZORPAY_SECRET))
        turf = models.Turf.objects.get(id = self.kwargs.get('turf_id'))
        payment = client.order.create(data = {"amount": turf.rent_per_hour * 100, "currency": "INR"})
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            'rent': turf.rent_per_hour,
            'order_id': payment['id'],
            'turf_id': self.kwargs.get('turf_id'),
        })
        return ctx

    def get_initial(self):
        intials =  super().get_initial()
        turf = models.Turf.objects.get(id = self.kwargs.get('turf_id'))
        intials.update({
            'user': self.request.user,
            'turf': turf,
        })
        return intials

class OwnerTurfBookingsView(LoginRequiredMixin, ListView):
    """
    this will show turf owner bookings
    """
    template_name = 'turf/turf_booking.html'

    def get_queryset(self):
        return models.Bookings.objects.filter(turf__owner = self.request.user)
        
class UserTurfBookingsView(LoginRequiredMixin, ListView):
    """
    this will show user bookings
    """
    template_name = 'turf/turf_bookings_user.html'

    def get_queryset(self):
        return models.Bookings.objects.filter(user = self.request.user)


def createpost(request):
        if request.method == 'POST':
            if request.POST.get('username')  and request.POST.get('ownername')  and request.POST.get('contact') and request.POST.get('turfdetails') and request.POST.get('complaint'):
                post=Post()
                post.username= request.POST.get('username')
                post.ownername= request.POST.get('ownername')
                post.contact= request.POST.get('contact')
                post.turfdetails= request.POST.get('turfdetails')
                post.complaint= request.POST.get('complaint')
                post.save()
                
                return render(request, 'turf/details.html')  

        else:
                return render(request,'turf/details.html')


def showvideo(request):
     alldata= Post.objects.all()
     context={'Post':alldata}
     return render(request,'turf/show.html',context)

turf_project/turfapp/templates/turf/add_turf.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <div class="form-group">
            <label for="exampleFormControlFile1">Upload images</label>
            <input class="image-input" type="file" name="image" accept="image/png, image/jpeg" multiple>
            <button id="add-image" class="btn btn-primary">Add more image</button>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
</div>
{% endblock content %}
{% block script %}
<script>
    $('#div_id_latitude, #div_id_longitude').wrapAll('<fieldset id="location_fieldset"></fieldset>')
    $('#location_fieldset').prepend('<legend>Location:</legend>');
    var count = 1;
    $('#add-image').on('click', function(e) {
        console.log(e);
        e.preventDefault()
        count++;    
        $(`<input class="image-input" type="file" name=${"image" + count} accept="image/png, image/jpeg"/> `).insertAfter($(".image-input").last())
    })
</script>
{% endblock script %}

turf_project/turfapp/templates/turf/booking_details.html
{% extends 'base.html' %}
{% block content %}
<style>
    img {
        max-width: 300px;
    }
</style>
<div class="container">
    <h1>Order Details</h1>
    <div class="col-md-5">
        <table class="table table-dark">
        <tbody>
            <tr>
                <th scope="row">Order Id</th>
                <td>{{object.order_id}}</td>
            </tr>
            <tr>
                <th scope="row">Booking Date</th>
                <td>{{object.date}}</td>
            </tr>
            <tr>
                <th scope="row">Booking Time</th>
                <td>{{object.time_from}} - {{object.time_to}}</td>
            </tr>
            <tr>
                <th scope="row">Turf name</th>
                <td>{{ object.turf.name }}</td>
            </tr>
            <tr>
                <th scope="row">Price paid</th>
                <td>$ {{ object.turf.rent_per_hour }}</td>
            </tr>
        </tbody>
    </table>
    <button class="btn btn-primary">Print</button>
    </div>
    
</div>
{% endblock content %}

turf_project/turfapp/templates/turf/booking_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .time-picker-container {
        display: flex;
        justify-content: space-around;
    }
    .time-picker {
        padding: 5px;
        background-color: blanchedalmond;
        border-radius: 3px;
        margin-bottom: 8px;
    }
    .time-picker-selected {
        border: 1px solid red;
    }
    .display-none {
        display: none;
    }
</style>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<div class="container">
    <div class="alert alert-danger display-none" id="error"></div>
    <form action="" method="post" id="form1">
        {{form | crispy}}
        {% csrf_token %}
        <input type="hidden" name="amount" value="{{ rent }}">
        <input type="hidden" name="order_id" value="{{ order_id }}">
        <label for="">Select any time:</label>
        <div class="time-picker-container">
            <div class="time-stamp">
                <h4>Morning</h4>
                <div class="time-picker" data-valueFrom="6:00" data-valueTo="7:00">6 am - 7 am</div>
                <div class="time-picker" data-valueFrom="7:00" data-valueTo="8:00">7 am - 8 am</div>
                <div class="time-picker" data-valueFrom="8:00" data-valueTo="9:00">8 am - 9 am</div>
                <div class="time-picker" data-valueFrom="9:00" data-valueTo="10:00">9 am - 10 am</div>
                <div class="time-picker" data-valueFrom="10:00" data-valueTo="11:00">10 am - 11 am</div>
                <div class="time-picker" data-valueFrom="11:00" data-valueTo="12:00">11 am - 12 pm</div>
            </div>
            <div class="time-stamp">
                <h4>Afternoon:</h4>
                <div class="time-picker" data-valueFrom="13:00" data-valueTo="14:00">1 pm - 2 pm</div>
                <div class="time-picker" data-valueFrom="14:00" data-valueTo="15:00">2 pm - 3 pm</div>
                <div class="time-picker" data-valueFrom="15:00" data-valueTo="16:00">3 pm - 4 pm</div>
                <div class="time-picker" data-valueFrom="16:00" data-valueTo="17:00">4 pm - 5 pm</div>
                <div class="time-picker" data-valueFrom="17:00" data-valueTo="18:00">5 pm - 6 pm</div>
            </div>
            <div class="time-stamp">
                <h4>Night:</h4>
                <div class="time-picker" data-valueFrom="18:00" data-valueTo="19:00">6 pm - 7 pm</div>
                <div class="time-picker" data-valueFrom="19:00" data-valueTo="20:00">7 pm - 8 pm</div>
                <div class="time-picker" data-valueFrom="20:00" data-valueTo="21:00">8 pm - 9 pm</div>
            </div>
        </div>
        <button id="rzp-button1" type="submit" class="btn btn-primary">Pay {{ rent }}</button>
    </form>
</div>
{% endblock content %}
{% block script %}
<script>
    var rent =  rent  * 100;
    var options = {
        "key": "rzp_test_lGPkBARO1wA5iz",
        "amount": rent, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
        "currency": "INR",
        // "name": "Acme Corp",
        // "description": "Test Transaction",
        "image": "https://example.com/your_logo",
        "order_id": "{{ order_id }}",
        "handler": function (response) {
            $("#id_razorpay_order_id").val(response.razorpay_order_id)
            $("#id_razorpay_payment_id").val(response.razorpay_payment_id)
            $("id_razorpay_signature").val(response.razorpay_signature)
            $("#form1").submit()
        },
        // "prefill": {
        //     "name": "Gaurav Kumar",
        //     "email": "gaurav.kumar@example.com",
        //     "contact": "9999999999"
        // },
        "notes": {
            "address": "Razorpay Corporate Office"
        },
        "theme": {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
    rzp1.on('payment.failed', function (response){
            alert(response.error.code);
            alert(response.error.description);
            alert(response.error.source);
            alert(response.error.step);
            alert(response.error.reason);
            alert(response.error.metadata.order_id);
            alert(response.error.metadata.payment_id);
    });
    document.getElementById('rzp-button1').onclick = function(e){
        e.preventDefault();
        var isTimeSelected = false;
        var dateSelected = false;
        $('.time-picker').each(function() {
            console.log($(this))
            if($(this).hasClass('time-picker-selected')) {
                console.log('found')
                isTimeSelected = true;
                return false;
            }
        })

        if($('#id_date').val() !== '') dateSelected = true;
        else dateSelected = false;


        if(isTimeSelected && dateSelected) {
            $.get(
                'http://127.0.0.1:8000/check-availablity/',
                {
                    date: $('#id_date').val(),
                    time_from: $('#id_time_from').val(),
                    turf_id: '{{turf_id}}',
                },
                function(data, status) {
                    if(data === 'ok') {
                        console.log('slot is available')
                        rzp1.open();
                        $('#error').addClass('display-none')
                    } else {
                        $('#error').text("This slot is already booked")
                        $('#error').removeClass('display-none')
                    }
                }
            )
        } else if(!isTimeSelected) {
            $('#error').text("You need to select any time!")
            $('#error').removeClass('display-none')
        } else if(!dateSelected) {
            $('#error').text("You need to select date!")
            $('#error').removeClass('display-none')
        }
    }

    $(".time-picker").click(function(e) {
        var time_from = $(this).attr('data-valueFrom');
        var time_to = $(this).attr('data-valueTo');
        $('.time-picker').removeClass('time-picker-selected');
        $(this).addClass('time-picker-selected');
        $('#id_time_from').val(time_from);
        $('#id_time_to').val(time_to);
    })
</script>
{% endblock script %}

turf_project/turfapp/templates/turf/details.html
<html>

            <body bgcolor="skyblue">


            <title>REGISTER COMPLAINTS</title>
            
             <table border=0 align="center">
                <form action="" method="POST">
                    {% csrf_token %}
                    <center>
                <h1>REGISTER COMPLAINTS</h1>
                </center>>

                <tr><td><b>UserName</b></td>
                <td><br><input type="text" name="username" ></td></tr>
            
                <tr><td><b>Ownername</b></td>
                <td><br><input type="text" name="ownername" ></td></tr>

                <tr><td><b>Contact</b></td>
                <td><br><input type="text" name="contact" ></td></tr>


            
                <tr><td><b>Turfdetails</b></td>
                <td><br><input type="text" name="turfdetails" ></td></tr>
                
                <tr><td><br><b>Complaint</b></td>
                <td><br><textarea name="complaint" cols="23" rows="5"></textarea></td></tr>
            
               
                
                <tr><td><b>     </b></td>
                <td><input type="submit" value="submit" /></td></tr>
                </form>
            </table>
            </body>
            


            </html>








	

turf_project/turfapp/templates/turf/show.html
{% load static %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html>
    <head>
        <title>PlayMakers</title>
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
        <!-- web-font -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,300,700,800,400,600' rel='stylesheet' type='text/css'>
        <!-- web-font -->
        <!-- js -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <!-- js -->
        <!-- start-smoth-scrolling -->
        <script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
        <script type="text/javascript">
            jQuery(document).ready(function($) {
                $(".scroll").click(function(event){		
                    event.preventDefault();
                    $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
                });
            });
        </script>
<!-- start-smoth-scrolling -->
<!-- animated-css -->
        <link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css" media="all">
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script>
         new WOW().init();
        </script>
<!-- animated-css -->
    <style>
        form input[type="text"] {
            padding: 0;
            margin-bottom: 0;
        }
    </style>
    </head>
    <body>
        <!-- header -->
        <div id="home" class="heder">
            <!-- container -->
            <div class="container">
                <div class="header-top">
                    <div class="heder-logo">
                        <h1><a href="#">PlayMakers</a></h1>
                    </div>
                    <div class="top-nav">
                    <span class="menu"><img src="{% static 'images/menu.png' %}" alt=""></span>
                        <ul class="nav1">

                            <li><a class="scroll" href="#home">Home</a></li>
                            <li><a class="scroll" href="#services">Services</a></li>
                            <li><a class="scroll" href="#portfolio">Works</a></li>
                            <li><a class="scroll" href="#about">About</a></li>
                            <li><a class="scroll" href="#contact">Contact</a></li>
                            <li><a class="Signup play-icon popup-with-zoom-anim" href="#small-dialog2">Sign up</a></li></ul>

                        </ul>
                        <!-- script-for-menu -->
                             <script>
                               $( "span.menu" ).click(function() {
                                 $( "ul.nav1" ).slideToggle( 300, function() {
                                 // Animation complete.
                                  });
                                 });
                            </script>
                        <!-- /script-for-menu -->
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
            <!-- container -->
        </div>
        
            <!-- container -->
        </div>
        
            <head>
            <meta charset="UTF-8">
            <title>complaints</title>
            </head>
            <body>
            
            
            
            <h1>List of complaints</h1>
            <table border="1" width="600">
            <tr>
            <td><br><b><center>Username</center></b></td>
            <td><br><b><center>Ownername</center></b></td>
            <td><br><b><center>Contact</center></b></td>
            <td><br><b><center>Turfdetails</center></b></td>
            <td><br><b><center>Complaint</center></b></td>
            </tr>
            
            {% for v in Post %}
            <tr>
            <td>{{ v.username }}</td>
            <td>{{ v.ownername }}</td>
            <td>{{ v.contact }}</td>
            <td>{{ v.turfdetails }}</td>
            <td>{{ v.complaint }}</td>
            
            
            
            </tr>
            {% endfor %}
            </table>
            
            
            </body>
            <script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpbh-mt'},{'server':'p3plmcpnl487010'},{'id':'8437534'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script><br><br><br>
            
            
            
            
            
            





        <!-- footer -->
        <div class="footer">
            <!-- container -->
            <div class="container">
                <h4>PlayMakers</h4>
                <div class="copyright">
                    <p>
                        Template by <a href="http://w3layouts.com/">W3layouts.com</a>
                    </p>
                </div>
                <a class="scroll" href="#home"><img src="{% static 'images/up-arrow.png' %}" alt="" /></a>
            </div>
            <!-- container -->
        </div>
        <!-- footer -->
    </body>
</html>

turf_project/turfapp/templates/turf/turf_booking.html
{% extends 'base.html' %}
{% block content %}
<style>
    .card {
        padding: 10px;
        width: 60rem;
        border: 1px solid grey;
        border-radius: 10px;
        margin: 5px;
    }
</style>
<div class="container">
    {% for obj in object_list %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Booked {{obj.turf.name }} </h5>
                <p class="card-text">
                    User: {{obj.user.username}} <br>
                    Booking Date : {{ obj.date }}
                    Time: {{ obj.time_from }} - {{ obj.time_to }}
                </p>
            </div>
        </div>
    {% empty %}
    <h1>Your turf have no bookings till now!</h1>
    {% endfor %}
</div>
{% endblock content %}